GenInsuranceApp/urls.py
from django.urls import path
from .views import *
#from django.contrib.auth import views as auth_views
app_name = 'GenInsuranceApp'
urlpatterns=[
    path('',home,name='GenInsuranceApp-home'),
    path('aboutus/',aboutus,name='GenInsuranceApp-aboutus'),
    path('login/',loginView,name='GenInsuranceApp-login'),
    path('signup/',signup,name= 'GenInsuranceApp-signup'),
    path('logout/',logout_view,name='GenInsuranceApp-logout'),
    path('main/',mainmenu,name='GenInsuranceApp-mainmenu'),
    #path('login1/',auth_views.loginView,{'template_name': 'General/login.html'},name='login')
]

GenInsurancePro/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = (
    path('admin/', admin.site.urls),
    path('', include('GenInsuranceApp.urls')),
    path('master/', include("master.urls")),
    path('underwriter/',include('underwriter.urls'))
)

master/urls.py
from django.urls import path
from .views import ProductsMaster,master,ProductRisk,AgentCreate,AgentCommission,vehicleMasterView,\
    vehicleDepreciationView,NCBMasterView,ClaimStatusMasterView,ClaimsSurveyorMasterView
app_name='master'

urlpatterns =[
    path("master/",master,name="master-master"),
    path("productmaster/",ProductsMaster,name = "master-ProductMaster"),
    path("productrisk/",ProductRisk,name="master-ProductRisk"),
    path('agentcreate/',AgentCreate,name = 'master-AgentCreate'),
    path('agentcommision/',AgentCommission,name='master-AgentCommision'),
    path('vehiclemaster/',vehicleMasterView,name='master-vehicleMasterView'),
    path('depriciation/',vehicleDepreciationView,name='master-vehicleDepreciationView'),
    path('ncb/',NCBMasterView,name='master-NCBMasterView'),
    path('claim/',ClaimStatusMasterView,name='master-ClaimStatusMasterView'),
    path('survey/',ClaimsSurveyorMasterView,name='master-ClaimsSurveyorMasterView'),

]

underwriter/urls.py
from django.urls import path
from .views import (InsuredcreateView,PolicyCreateView,underwriter)
#from .Utilities import get_risk_details
app_name = 'underwriter'

urlpatterns = [
    path('underwriter/',underwriter,name='underwriter'),
    path('CreateInsured/', InsuredcreateView, name='CreateInsured'),
    path('PolicyCreate/', PolicyCreateView, name='PolicyCreate'),
]

underwriter/forms.py
from django import forms
from .models import InsureDetails,InsuredAddress,policyAgentCommision,policyVehicleDetails,policyRiskDetails,PolicyDetails,PolicyBills
from master.models import ProductRiskMaster
from master.models import VehicleMaster
from datetime import datetime,date, timedelta
month = {"1":"JAN","2":"FEB","3":"MAR","4":"APR","5":"MAY","6":"JUN","7":"JUL","8":"AUG","9":"SEP","10":"OCT","11":"NOV","12":"DEC"}

class InsuredDetailsForms(forms.ModelForm):

    insured_dob = forms.DateField(widget=forms.SelectDateWidget(months=month,years = range(1980,2050)))
    class Meta:
        model = InsureDetails
        fields='__all__'

        exclude=[
            'created_by','last_updated_by'
        ]


class InsuredAddressForm(forms.ModelForm):
    address_type = (
        ("","------"),
        ("T","Temporary"),
        ("P","Permanent")
    )
    class Meta:
        model=InsuredAddress

        fields="__all__"
        exclude=[
            'created_by','last_updated_by',"insured_id"
        ]

class policyDetailsForm(forms.ModelForm):
    policy_issued_date = forms.DateField(widget=forms.SelectDateWidget(),
                                         initial=date.today())

    start_date = forms.DateField(widget=forms.SelectDateWidget(),
                                 initial=date.today() + timedelta(days=1))
    end_date = forms.DateField(widget=forms.SelectDateWidget(),
                               initial=date.today() + timedelta(days=365))
    policy_status = (
        ('', '---------'),
        ('QUOTE', ("Quotation")),
        ('PAYMENTPENDING', ("Payment Pending")),
        ('INFORCE', ("Inforce")),
        ('LAPSE', ("Policy Lapse"))
    )
    payment_mode = (
        ('', '---------'),
        ('Q', ("Quartely")),
        ('H', ("Harl Yearly")),
        ('A', ("Annual"))
    )

    policy_status = forms.ChoiceField(choices=policy_status, required=False)
    payment_mode = forms.ChoiceField(choices=payment_mode, required=False)
    policy_no = forms.IntegerField(initial=PolicyDetails.objects.count() + 1)
    renewal_no = forms.IntegerField(initial=0)

    class Meta:
        model = PolicyDetails
        fields = '__all__'
        #[
        #     'policy_no',
        #     'insured_id',
        #     'prod_code',
        #     'agent_code',
        #     'policy_issued_date',
        #     'start_date',
        #     'end_date',
        #     'policy_status',
        #     'renewal_no',
        #     'payment_mode',
        #     'total_premium',
        #     'created_by',
        #     'last_updated_by'
        # ]

        exclude = ['created_by',
                   'last_updated_by']

class VehicleDtlsForm(forms.ModelForm):

    mfg_comp = VehicleMaster.objects.values_list('mfg_company_name',flat=True).distinct()
    mfg_comp_choices = [('', 'None')] + [(id, id) for id in mfg_comp]

    model_id = VehicleMaster.objects.values_list('model_id', flat=True).distinct()
    model_id_choices = [('', 'None')] + [(id, id) for id in model_id]

    model_name = VehicleMaster.objects.values_list('model_name', flat=True).distinct()
    model_name_choices = [('', 'None')] + [(id, id) for id in model_name]

    vehicle_make = forms.ChoiceField(choices=mfg_comp_choices, required=False, widget=forms.Select())
    vehicle_model_id = forms.ChoiceField(choices=model_id_choices, required=False, widget=forms.Select())
    vehicle_model_name = forms.ChoiceField(choices=model_name_choices, required=False, widget=forms.Select())

    class Meta:
        model = policyVehicleDetails
        fields = '__all__'
        #     [
        #     'policy_no',
        #     'vehicle_year',
        #     'vehicle_make',
        #     'vehicle_model_id',
        #     'vehicle_model_name',
        #     'chasis_number',
        #     'engine_number',
        #     'created_by',
        #     'last_updated_by'
        # ]

        exclude = ['policy_no','created_by',
                   'last_updated_by']

class PolicyRiskDtlsForm(forms.ModelForm):
    start_date = forms.DateField(widget=forms.SelectDateWidget(),
                                 initial=date.today()+timedelta(days=1))
    end_date = forms.DateField(widget=forms.SelectDateWidget())

    class Meta:
        model = policyRiskDetails
        fields = '__all__'
        #     [
        #     'policy_no',
        #     'risk_code',
        #     'risk_description',
        #     'risk_SA',
        #     'risk_premium',
        #     'start_date',
        #     'end_date',
        #     'created_by',
        #     'last_updated_by'
        # ]

        exclude = ['policy_no','created_by','last_updated_by']

class PolicyBillsForm(forms.ModelForm):
    class Meta:
        model = PolicyBills
        fields = '__all__'
        #     [
        #     'bill_id',
        #     'policy_no',
        #     'premium_amount',
        #     'due_date',
        #     'balance_amount',
        #     'created_by',
        #     'last_updated_by'
        # ]
        exclude = ['created_by','last_updated_by']

underwriter/views.py
from django.shortcuts import render,redirect
from django.forms import modelformset_factory
from .forms import InsuredDetailsForms,InsuredAddressForm,policyDetailsForm,VehicleDtlsForm,PolicyRiskDtlsForm
from .models import InsureDetails,InsuredAddress,policyRiskDetails,PolicyDetails
from master.models import VehicleMaster
from django.db import transaction, IntegrityError
from .premiumCalc import motor_Risk_prem_calc
# Create your views here.

def underwriter(request):
    return render(request,'underwriter/underwriterdata.html')
def InsuredcreateView(request):
    context = {}
    InsuredAddrFormset = modelformset_factory(InsuredAddress, form=InsuredAddressForm,extra=2)
    Insuredform = InsuredDetailsForms(request.POST or None)
    formset = InsuredAddrFormset(request.POST or None)

    if request.method == "POST":
        if Insuredform.is_valid() and formset.is_valid():
            try:
                with transaction.atomic():
                    insured = Insuredform.save(commit=False)
                    print('12insured', insured.insured_id)
                    print('12insured', insured.insured_name)
                    insured.save()
                    for mark in formset:
                        data = mark.save(commit=False)
                        if not data.address_Type is None:
                            print('data.address_Type',data.address_Type)
                            print('data.insured_id', data.insured_id)
                            print('34insured',insured)
                            data.insured_id = insured
                            data.save()

            except IntegrityError:
                print("Error Encountered",IntegrityError.__name__)

    Insuredform = InsuredDetailsForms()
    formset = InsuredAddrFormset(queryset=InsuredAddress.objects.none())

    context = {
        "formset":formset,
        "form":Insuredform
    }
    #context['formset'] = formset
    #context['form'] = Insuredform
    return render(request, 'underwriter/InsuredCreate.html', context)

def PolicyCreateView(request):
    context = {}
    PolicyForm = policyDetailsForm(request.POST or None)
    VehicleForm = VehicleDtlsForm(request.POST or None)

    RiskFormset = modelformset_factory(policyRiskDetails, form=PolicyRiskDtlsForm, extra=3)
    formset = RiskFormset(request.POST or None)

    if request.method == "POST":

        if PolicyForm.is_valid():
            print(PolicyForm.cleaned_data)
            try:
                with transaction.atomic():
                    policy = PolicyForm.save(commit=False)
                    print('policy no:', policy.policy_no)
                    policy.created_by = str(request.user)
                    policy.last_updated_by = str(request.user)
                    policy.save()


                if VehicleForm.is_valid():
                    vehicle = VehicleForm.save(commit=False)
                    vehicle.created_by = str(request.user)
                    vehicle.last_updated_by = str(request.user)
                    print('vehicle data :', VehicleForm.cleaned_data)
                    vehicle.policy_no = policy
                    vehicle.created_by = str(request.user)
                    vehicle.last_updated_by = str(request.user)
                    print('No policy', vehicle.policy_no)
                    l_year =vehicle.vehicle_year
                    l_make = vehicle.vehicle_make
                    l_model = vehicle.vehicle_model_id
                    l_model_name = vehicle.vehicle_model_name
                    vehicle.save()

                l_tot_prem = 0
                if formset.is_valid():
                    for risk in formset:
                        data = risk.save(commit=False)
                        if not data.risk_code is None:
                            print('Riskcode', data.risk_code)
                            print('l_year',l_year)

                            data.policy_no = policy
                            data.created_by = str(request.user)
                            data.last_updated_by = str(request.user)
                            data.risk_description,data.risk_SA, data.risk_premium = \
                                motor_Risk_prem_calc(data.risk_code,l_year,l_make,l_model,l_model_name)
                            l_tot_prem = l_tot_prem + data.risk_premium
                            print('l_tot_prem',l_tot_prem)
                            policy.total_premium=l_tot_prem
                            data.save()
                print('l_tot_prem', l_tot_prem)
                policy.save()
            except IntegrityError as e:
                print("Error Encountered", e.__context__)

    PolicyForm = policyDetailsForm()
    VehicleForm = VehicleDtlsForm()
    formset = RiskFormset(queryset=policyRiskDetails.objects.none())

    context['Policyform'] = PolicyForm
    context['VehicleForm'] = VehicleForm
    context['PolicyRishForm'] = formset
    return render(request, 'underwriter/CreatePolicy.html', context)

templates/underwriter/CreatePolicy.html
{% extends 'base.html' %}
{% block style %}
{% endblock %}
{% block javascript %}

  <script>
    $("#id_form-0-policy_risk_id").change(function () {
      var username = $(this).val();
      $.ajax({
        url: '/underwrite/get_risk/',
        data: {
          'username': username
        },
        dataType: 'json',
        success: function (data) {
          if (data.is_taken) {
            alert("A user with this username already exists.");
          }
        }
      });

    });
  </script>
{% endblock %}

{% block content %}
   <form method="POST">
      {% csrf_token %}
        <div>
            <a  href='{% url "underwriter:CreateInsured" %}' class="btn btn-primary" role="button"> Insured Creation </a>
        </div>
        <div class="hdrin">
            <h5>Policy Details</h5> <br>
        </div>
            <div class="in">
                <div class="row">
                    {{ Policyform.as_p }}
                </div>
            </div>

        <div class="hdrin">
            <h5>Vehicle Details</h5> <br>
        </div>
            <div class="in" align="center">
            <div class="row">
                    {{ VehicleForm.as_p }}
                </div>
                    </div>
        <div class="hdrin">
            <h5>Risk Details</h5> <br>
        </div>
        <div class="in">
            {{ PolicyRishForm.non_form_errors.as_ul }}
                {{ PolicyRishForm.management_form }}
                <table id="formset" class="form">
                {% for form in PolicyRishForm.forms %}
                  {% if forloop.first %}
                  <thead><tr>
                    {% for field in form.visible_fields %}
                    <th>{{ field.label|capfirst }}</th>
                    {% endfor %}
                  </tr></thead>
                  {% endif %}
                  <tr class="{% cycle row1 row2 %}">
                  {% for field in form.visible_fields %}
                    <td>
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                      {% for hidden in form.hidden_fields %}
                      {{ hidden }}
                      {% endfor %}
                    {% endif %}
                      {{ field.errors.as_ul }}
                      {{ field }}
                    </td>
                  {% endfor %}
                  </tr>
                {% endfor %}
                </table>
        </div>

                <div align="right">
                    <input type='submit' name="Create" value='Create' >

        </div>
        </div>
    </form>
{% endblock %}

templates/underwriter/InsuredCreate.html
{% extends 'base.html' %}
{% block content %}
   <form method="POST">
      {% csrf_token %}
        <div class="hdrin">
            <h5>Insured Details</h5> <br>
        </div>
      <div class="in" align="center">
        {{ form.as_p }}

        </div>
        <div class="hdrin">
            <h5>Insured Address Details</h5> <br>
        </div>
        <div class="in">
            <div class="row">
                    {{ formset.non_form_errors.as_ul }}
                {{ formset.management_form }}
                <table id="formset" class="form">
                {% for form in formset.forms %}
                  {% if forloop.first %}
                  <thead><tr>
                    {% for field in form.visible_fields %}
                    <th>{{ field.label|capfirst }}</th>
                    {% endfor %}
                  </tr></thead>
                  {% endif %}
                  <tr class="{% cycle row1 row2 %}">
                  {% for field in form.visible_fields %}
                    <td>
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                      {% for hidden in form.hidden_fields %}
                      {{ hidden }}
                      {% endfor %}
                    {% endif %}
                      {{ field.errors.as_ul }}
                      {{ field }}
                    </td>
                  {% endfor %}
                  </tr>
                {% endfor %}
                </table>
             </div>
    </div>
                <div align="right">
            <button type="submit">Submit</button>
        </div>
    </form>
{% endblock %}

templates/underwriter/underwriterdata.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MasterPage</title>
</head>
<body>
<h2 align="center">This is my underwriter Page</h2>
<p align="right"> <a href="{% url 'GenInsuranceApp:GenInsuranceApp-logout' %}" class="btn btn-danger" role="button">Logout</a>
     <a align="right" href="{% url 'GenInsuranceApp:GenInsuranceApp-mainmenu' %}" class="btn btn-danger" role="button">Mainmenu</a></p>
    <p align="center"><a href="{% url 'underwriter:CreateInsured' %}" class="btn btn-primary" role="button">Create Insured</a></p>
<p align="center"><a href="{% url 'underwriter:PolicyCreate' %}" class="btn btn-primary" role="button">Policy Create</a></p>
</body>
</html>