GenInsuranceApp/urls.py
from django.urls import path
from .views import *
#from django.contrib.auth import views as auth_views
app_name = 'GenInsuranceApp'
urlpatterns=[
    path('',home,name='GenInsuranceApp-home'),
    path('aboutus/',aboutus,name='GenInsuranceApp-aboutus'),
    path('login/',loginView,name='GenInsuranceApp-login'),
    path('signup/',signup,name= 'GenInsuranceApp-signup'),
    path('logout/',logout_view,name='GenInsuranceApp-logout'),
    path('main/',mainmenu,name='GenInsuranceApp-mainmenu'),
    #path('login1/',auth_views.loginView,{'template_name': 'General/login.html'},name='login')
]

GenInsurancePro/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = (
    path('admin/', admin.site.urls),
    path('', include('GenInsuranceApp.urls')),
    path('master/', include("master.urls")),
    path('underwriter/',include('underwriter.urls'))
)

master/urls.py
from django.urls import path
from .views import ProductsMaster,master,ProductRisk,AgentCreate,AgentCommission,vehicleMasterView,\
    vehicleDepreciationView,NCBMasterView,ClaimStatusMasterView,ClaimsSurveyorMasterView
app_name='master'

urlpatterns =[
    path("master/",master,name="master-master"),
    path("productmaster/",ProductsMaster,name = "master-ProductMaster"),
    path("productrisk/",ProductRisk,name="master-ProductRisk"),
    path('agentcreate/',AgentCreate,name = 'master-AgentCreate'),
    path('agentcommision/',AgentCommission,name='master-AgentCommision'),
    path('vehiclemaster/',vehicleMasterView,name='master-vehicleMasterView'),
    path('depriciation/',vehicleDepreciationView,name='master-vehicleDepreciationView'),
    path('ncb/',NCBMasterView,name='master-NCBMasterView'),
    path('claim/',ClaimStatusMasterView,name='master-ClaimStatusMasterView'),
    path('survey/',ClaimsSurveyorMasterView,name='master-ClaimsSurveyorMasterView'),

]

templates/General/aboutUs.html
{% extends 'base.html' %}
{% block title %}
<title>Aboutus</title>
{% endblock %}
{% block content %}
    <h1>This is My AboutUs Page</h1><br>
    <a href="{% url 'GenInsuranceApp:GenInsuranceApp-login' %}" class="btn btn-primary" role="button">Signin</a>
<a href="{% url 'GenInsuranceApp:GenInsuranceApp-home' %}" class="btn btn-primary" role="button">Home</a>
{% endblock %}

templates/General/login.html
{% extends 'base.html' %}
{% block title %}
    <title>Login</title>
{% endblock %}
style{
{% block content %}
    <form method="POST">
    {% csrf_token %}
        <fieldset>
            <legend><b>User Login</b></legend>
                Username:<input type="text" name="username"/>
                <br/><br/>
                Password:<input type="password" name="password">
                <br/><br/>
                <input type="submit" value="signin">
        </fieldset>
    </form>
<br>
<a href="{% url 'GenInsuranceApp:GenInsuranceApp-signup' %}" class="btn btn-primary" role="button">Register</a>
<a href="{% url 'GenInsuranceApp:GenInsuranceApp-home' %}" class="btn btn-primary" role="button">Home</a>


{% endblock %}

templates/General/logout.html
{% extends 'base.html' %}
{% block content %}
<h1 align="center">Logged Out</h1>
<br><br>
    <a href="{% url 'GenInsuranceApp:GenInsuranceApp-home' %}" class="btn btn-primary" role="button">Home</a><br>
<a href="{% url 'GenInsuranceApp:GenInsuranceApp-login' %}" class="btn btn-primary" role="button">Login</a>

{% endblock %}

templates/General/signup.html
{% extends 'base.html' %}
{% block title %}
    <title>Signup</title>
{% endblock %}
{% block content %}
<h2>This is our Registration Page</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register"><br>
    <br>
<a href="{% url 'GenInsuranceApp:GenInsuranceApp-home' %}" class="btn btn-primary" role="button">Home</a>
<a href="{% url 'GenInsuranceApp:GenInsuranceApp-login' %}" class="btn btn-primary" role="button">Login</a>
</form>
{% endblock %}