GenInsuranceApp/urls.py
from django.urls import path
from .views import *
#from django.contrib.auth import views as auth_views
app_name = 'GenInsuranceApp'
urlpatterns=[
    path('',home,name='GenInsuranceApp-home'),
    path('aboutus/',aboutus,name='GenInsuranceApp-aboutus'),
    path('login/',loginView,name='GenInsuranceApp-login'),
    path('signup/',signup,name= 'GenInsuranceApp-signup'),
    path('logout/',logout_view,name='GenInsuranceApp-logout'),
    path('main/',mainmenu,name='GenInsuranceApp-mainmenu'),
    #path('login1/',auth_views.loginView,{'template_name': 'General/login.html'},name='login')
]

GenInsurancePro/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = (
    path('admin/', admin.site.urls),
    path('', include('GenInsuranceApp.urls')),
    path('master/', include("master.urls")),
    path('underwriter/',include('underwriter.urls'))
)

master/urls.py
from django.urls import path
from .views import ProductsMaster,master,ProductRisk,AgentCreate,AgentCommission,vehicleMasterView,\
    vehicleDepreciationView,NCBMasterView,ClaimStatusMasterView,ClaimsSurveyorMasterView
app_name='master'

urlpatterns =[
    path("master/",master,name="master-master"),
    path("productmaster/",ProductsMaster,name = "master-ProductMaster"),
    path("productrisk/",ProductRisk,name="master-ProductRisk"),
    path('agentcreate/',AgentCreate,name = 'master-AgentCreate'),
    path('agentcommision/',AgentCommission,name='master-AgentCommision'),
    path('vehiclemaster/',vehicleMasterView,name='master-vehicleMasterView'),
    path('depriciation/',vehicleDepreciationView,name='master-vehicleDepreciationView'),
    path('ncb/',NCBMasterView,name='master-NCBMasterView'),
    path('claim/',ClaimStatusMasterView,name='master-ClaimStatusMasterView'),
    path('survey/',ClaimsSurveyorMasterView,name='master-ClaimsSurveyorMasterView'),

]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
{% block style %}
{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
{% block title%}
{% endblock %}
<link href="{% static 'CSS/base.css' %}" rel="stylesheet">
</head>
    <body>
{% block content %}
{% endblock %}
    </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block style %}
<style>
body {
    background-image: url("/static/images/total2.jpg");
}
</style>
{% endblock %}
{% block content %}

    <h1 align="center">Here to start to Insurance</h1>
    <div class="alert alert-warning">
    <strong>
        <a href="{% url 'GenInsuranceApp:GenInsuranceApp-aboutus' %}" class="btn btn-primary" role="button">AboutUs</a>
        <a href="{% url 'GenInsuranceApp:GenInsuranceApp-login' %}" class="btn btn-primary" role="button">Login</a>
        <a href="{% url 'GenInsuranceApp:GenInsuranceApp-signup' %}" class="btn btn-primary" role="button">Register</a>
    </strong>
    </div>




{% endblock %}