GenInsuranceApp/urls.py
from django.urls import path
from .views import *
#from django.contrib.auth import views as auth_views
app_name = 'GenInsuranceApp'
urlpatterns=[
    path('',home,name='GenInsuranceApp-home'),
    path('aboutus/',aboutus,name='GenInsuranceApp-aboutus'),
    path('login/',loginView,name='GenInsuranceApp-login'),
    path('signup/',signup,name= 'GenInsuranceApp-signup'),
    path('logout/',logout_view,name='GenInsuranceApp-logout'),
    path('main/',mainmenu,name='GenInsuranceApp-mainmenu'),
    #path('login1/',auth_views.loginView,{'template_name': 'General/login.html'},name='login')
]

GenInsurancePro/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = (
    path('admin/', admin.site.urls),
    path('', include('GenInsuranceApp.urls')),
    path('master/', include("master.urls")),
    path('underwriter/',include('underwriter.urls'))
)

master/urls.py
from django.urls import path
from .views import ProductsMaster,master,ProductRisk,AgentCreate,AgentCommission,vehicleMasterView,\
    vehicleDepreciationView,NCBMasterView,ClaimStatusMasterView,ClaimsSurveyorMasterView
app_name='master'

urlpatterns =[
    path("master/",master,name="master-master"),
    path("productmaster/",ProductsMaster,name = "master-ProductMaster"),
    path("productrisk/",ProductRisk,name="master-ProductRisk"),
    path('agentcreate/',AgentCreate,name = 'master-AgentCreate'),
    path('agentcommision/',AgentCommission,name='master-AgentCommision'),
    path('vehiclemaster/',vehicleMasterView,name='master-vehicleMasterView'),
    path('depriciation/',vehicleDepreciationView,name='master-vehicleDepreciationView'),
    path('ncb/',NCBMasterView,name='master-NCBMasterView'),
    path('claim/',ClaimStatusMasterView,name='master-ClaimStatusMasterView'),
    path('survey/',ClaimsSurveyorMasterView,name='master-ClaimsSurveyorMasterView'),

]

master/forms.py
from django import forms
from master.models import AgentMaster,ProductMaster,ProductRiskMaster,Agent_prod_comm_Master,\
    VehicleMaster,VehicleDepriciation,NCBMaster,ClaimStatusMaster,ClaimsSurveyorMaster
import datetime
# class AgentForm(forms.ModelForm):
#     class Meta:
#         model = AgentMaster
#         fields = "__all__"



class ProductMasterForm(forms.ModelForm):
    prod_start_date = forms.DateField(widget=forms.SelectDateWidget(),initial=datetime.date.today())
    prod_end_date = forms.DateField(widget=forms.SelectDateWidget())

    class Meta:
        model=ProductMaster
        fields = [
            'prod_code',
            'prod_description',
            'prod_start_date',
            'prod_end_date',
            'created_by',
            'last_updated_by'
        ]
        exclude=[
            'created_by',
            'last_updated_by'
        ]


    def clean_prod_code(self,*args,**kwargs):
        data = self.cleaned_data['prod_code']
        print("product data",data)
        if not data.isupper():
            raise forms.ValidationError("Prod code should be in Upper case")
        if '@' in data or "*" in data or "|" in data:
            raise forms.ValidationError("Prod code should not have special character")
        if len(data)<5:
            self._errors['prod_code'] = self.error_class(["Minimum 5 characters required"])

        return data

    def clean(self):
        super(ProductMasterForm,self).clean()
        prod_desc = self.cleaned_data.get('prod_description')
        if len(prod_desc)<10:
            self._errors['prod_description'] = self.error_class(["Product Description is not less than 10 Characters"])
        return self.cleaned_data


class ProductRiskForm(forms.ModelForm):

    cal_method = (
        ("","--------"),
        ("F","Fixed"),
        ("P","Percentage")
    )
    risk_start_date = forms.DateField(widget=forms.SelectDateWidget(),required=False)
    risk_end_date = forms.DateField(widget=forms.SelectDateWidget(),required=False)
    risk_code = forms.CharField(widget=forms.TextInput(attrs={"size":10}),required=True)
    risk_description  = forms.CharField(widget=forms.TextInput(attrs={"size":10}),required=True)
    risk_premium_percent = forms.DecimalField(required=False)
    prem_calc_method = forms.ChoiceField(choices=cal_method,required=False)

    class Meta:
        model = ProductRiskMaster
        fields=[
            'prod_code',
            'risk_code',
            'risk_description',
            'risk_premium_percent',
            'risk_end_date',
            'risk_start_date',
            'fixed_premium',
            'fixed_si',
            'created_by',
            'last_updated_by'
        ]
        exclude=[
            'created_by','last_updated_by'
        ]
    def clean_risk_code(self,*args,**kwargs):
        data = self.cleaned_data['risk_code']
        if not data.isupper():
            raise forms.ValidationError("risk_code code should be in upper case")
        if "@" in data or "*" in data or "|" in data:
            raise forms.ValidationError("risk_code code should not contain @,*,|")
        if len(data) < 5 :
            self._errors['risk_code']=self.error_class(["Minimum 5 charcters required"])
        return data
    def clean_risk_premium_percent(self,*args,**kwargs):
        data = self.cleaned_data['risk_premium_percent']
        if data is None:
            print("is none")
        else:
            if data>100:
                raise forms.ValidationError("Premium percent should not exceed 100")
        return data

    def clean(self):
        super(ProductRiskForm,self).clean()
        risk_desc = self.cleaned_data.get('risk_description')
        calmethod = self.cleaned_data.get('prem_calc_method')

        if calmethod == "F":
            if self.cleaned_data.get('fixed_premium')==""or self.cleaned_data.get('fixed_premium') or None:
                self._errors['fixed_premium'] = self.error_class([
                    "Fixed premium should not be null when premium calc method is fixed"
                ])
            if self.cleaned_data.get("fixed_si") == "" or self.cleaned_data.get("fixed_si") or None:
                self._errors['fixed_si'] = self.error_class([
                    "Fixed si should not be null when premium calc method is percntage"
                ])
        elif calmethod == "P":
            print('percent',self.cleaned_data.get('risk_premium_percent'))
            if self.cleaned_data.get("risk_premium_percent") is None:
                self._errors["risk_premium_percent"]=self.error_class([
                    "risk_premium_percent should not be null When premium  calc method is percentage"
                ])
        return self.cleaned_data

class AgentCreateForm(forms.ModelForm):
    agent_checkbox=[
        ('Active','Active'),
        ('Deactive','Deactive')
    ]
    month = {'jan':'jan','feb':'feb','mar':'mar','apr':'apr','may':'may','jun':'jun','jul':'jul','aug':'aug',
             'sep':'sep','oct':'oct','nov':'nov','dec':'dec'}
    agent_dob = forms.DateField(widget=forms.SelectDateWidget(months=month,years=range(1980,2030)))
    agent_start_date = forms.DateField(widget=forms.SelectDateWidget(months=month))
    agent_end_date = forms.DateField(widget=forms.SelectDateWidget(months=month),required=False)
    agent_status = forms.ChoiceField(choices=agent_checkbox,required=False)
    class Meta:
        model = AgentMaster

        fields = [
            'agent_id',
            'agent_age',
            'agent_name',
            'agent_dob',
            'agent_qualification',
            'agent_join_date',
            'agent_end_date',
            'agent_start_date',
            'agent_status',
            'created_by',
            'last_updated_by'
        ]
        exclude=[
            'agent_id','agent_age','created_by','last_updated_by'
        ]

class AgentCommissionForm(forms.ModelForm):
    class Meta:
        model = Agent_prod_comm_Master
        fields = [
            'agent_id',
            'prod_code',
            'comm_percent',
            'created_by',
            'last_updated_by'
        ]
        exclude = [
            'created_by','last_updated_by'
        ]

class VehicleMasterForm(forms.ModelForm):

    class Meta:
        model= VehicleMaster

        fields = [
            'mfg_company_name',
            'model_id',
            'model_name',
            'engine_cubic_capacity',
            'insured_declared_value',
            'created_by',
            'last_updated_by'
        ]
        exclude=[
            'created_by','last_updated_by'
        ]

class vehicleDepriciationForm(forms.ModelForm):
    class Meta:
        model=VehicleDepriciation
        fields=[
            'vehicle_age_from',
            'vehicle_age_to',
            'dep_percent_on_idv',
            'created_by',
            'last_updated_by'
        ]
        exclude=[
            'created_by','last_updated_by'
        ]


class NCBMasterForm(forms.ModelForm):
    class Meta:
        model = NCBMaster

        fields=[
            'prod_code',
            'no_of_years_from',
            'no_of_years_to',
            'discount_on_premium',
            'discount_desc',
            'created_by',
            'last_updated_by'
        ]
        exclude = [
            'created_by','last_updated_by'
        ]


class ClaimStatusMasterForm(forms.ModelForm):
    class Meta:
        model =ClaimStatusMaster
        fields = [
            'clm_status_code',
            'clm_status_desc',
            'created_by',
            'last_updated_by'
        ]
        exclude = [
            'created_by','last_updated_by'
        ]

class ClaimsSurveyorMasterForm(forms.ModelForm):
    class Meta:
        model = ClaimsSurveyorMaster
        fields='__all__'
        '''    [
             'surveyor_id',
             'surveyor_name',
             'surveyor_city',
             'surveyor_qualificaition',
             'surveyor_brach_code'
             'phone',
             'created_by',
             'last_updated_by'
         ]
        '''
        exclude = [
            'created_by','last_updated_by','surveyor_id'
        ]

master/views.py
from django.shortcuts import render,get_object_or_404
from .models import ProductMaster,ProductRiskMaster,AgentMaster,Agent_prod_comm_Master
from .forms import ProductMasterForm,ProductRiskForm,AgentCreateForm,AgentCommissionForm,VehicleMasterForm,\
    vehicleDepriciationForm,NCBMasterForm,ClaimStatusMasterForm,ClaimsSurveyorMasterForm
from django.contrib.auth.decorators import login_required
from django.forms import modelformset_factory
# Create your views here.

def master(request):
    return render(request,'Master/masterdata.html')

@login_required(login_url='/admin1/login/')
def ProductsMaster(request):
    pform = ProductMasterForm(request.POST or None)
    if pform.is_valid():
        form = pform.save(commit=False)
        form.created_by = str(request.user)
        form.last_updated_by = str(request.user)
        form.save()
        pform = ProductMasterForm()
    context = {"pform":pform}
    return render(request,"Master/ProductMaster.html",context)

def ProductRisk(request):
    cformset = modelformset_factory(ProductRiskMaster,form=ProductRiskForm,extra =2,can_delete=True)
    formset = cformset(request.POST or None)
    if formset.is_valid():
        for form in formset.forms:
            if form['risk_code'].value() !="":
                for name,fields in form.fields.items():
                    tmpform = form.sve(commit=False)
                    setattr(tmpform,'created_by',str(request.user))
                    setattr(tmpform,'last_updated_by',str(request.user))
    context = {'formset':formset}
    return render(request,'Master/productRisk.html',context)



def AgentCreate(request):
    Aform = AgentCreateForm(request.POST or None)
    if Aform.is_valid():
        form = Aform.save(commit=False)
        form.created_by = str(request.user)
        form.last_updated_by = str(request.user)
        form.save()
        Aform = AgentCreateForm()
    context = {'Aform':Aform}
    return render(request,'Master/Agentcreate.html',context)


def AgentCommission(request):
    cformset = modelformset_factory(Agent_prod_comm_Master,form=AgentCommissionForm,extra=2)
    formset = cformset(request.POST or None)
    if formset.is_valid():
        for form in formset.forms:
            print('agentform',form)
            if form['agent_id'].value() !="":
                for name,fields in form.fields.items():
                    print('name',name)
                    print('fields',fields)
                    tmpform = form.save(commit=False)
                    setattr(tmpform,'created_by',str(request.user))
                    setattr(tmpform,'last_updated_by',str(request.user))
                    tmpform.save()
    context = {'formset':formset}
    return render(request,'Master/AgentCommision.html',context)


def vehicleMasterView(request):
    vform = VehicleMasterForm(request.POST or None)
    if vform.is_valid():
        form = vform.save(commit=False)
        form.created_by=str(request.user)
        form.last_updated_by=str(request.user)
        form.save()
        vform = VehicleMasterForm()
    context = {'vform':vform}
    return render(request,'Master/vehiclemaster.html',context)


def vehicleDepreciationView(request):
    vform = vehicleDepriciationForm(request.POST or None)
    if vform.is_valid():
        form = vform.save(commit=False)
        form.created_by=str(request.user)
        form.last_updated_by = str(request.user)
        form.save()
        vform = vehicleDepriciationForm()
    context = {'vform':vform}
    return render(request,'Master/vehicledepriciation.html',context)


def NCBMasterView(request):
    nform = NCBMasterForm(request.POST or None)
    if nform.is_valid():
        form = nform.save(commit=False)
        form.created_by = str(request.user)
        form.last_updated_by = str(request.user)
        form.save()
        nform = NCBMasterForm()
    context = {'nform':nform}
    return render(request,'Master/ncbmaster.html',context)


def ClaimStatusMasterView(request):
    cform = ClaimStatusMasterForm(request.POST or None)
    if cform.is_valid():
        form = cform.save(commit=False)
        form.created_by = str(request.user)
        form.last_updated_by = str(request.user)
        form.save()
        cform = ClaimStatusMasterForm()
    context = {'cform':cform}
    return render(request,'Master/claimstatus.html',context)


def ClaimsSurveyorMasterView(request):
    csform = ClaimsSurveyorMasterForm(request.POST or None)
    if csform.is_valid():
        form = csform.save(commit=False)
        form.created_by = str(request.user)
        form.last_updated_by = str(request.user)
        form.save()
    context = {'csform':csform}
    return render(request,'Master/claimsurveyor.html',context)

templates/Master/AgentCommision.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
{% csrf_token %}
    <p align="right"> <a href="{% url 'GenInsuranceApp:GenInsuranceApp-logout' %}" class="btn btn-danger" role="button">Logout</a>
     <a align="right" href="{% url 'GenInsuranceApp:GenInsuranceApp-mainmenu' %}" class="btn btn-danger" role="button">Mainmenu</a></p>
{{ formset.as_p }}
<br>
<input type="submit" value="submit" name="submit">
</form>
{% endblock %}

templates/Master/Agentcreate.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
{% csrf_token %}
    <p align="right"> <a href="{% url 'GenInsuranceApp:GenInsuranceApp-logout' %}" class="btn btn-danger" role="button">Logout</a>
     <a align="right" href="{% url 'GenInsuranceApp:GenInsuranceApp-mainmenu' %}" class="btn btn-danger" role="button">Mainmenu</a></p>
{{ Aform.as_p }}
<input type="submit" value="submit" name="submit">
</form>
{% endblock %}

templates/Master/ProductMaster.html
{% extends 'base.html' %}
{% block content %}
<h1>This is My Product Master Page</h1>
    <form method="POST">
    {% csrf_token %}
        <p align="right"> <a href="{% url 'GenInsuranceApp:GenInsuranceApp-logout' %}" class="btn btn-danger" role="button">Logout</a>
     <a align="right" href="{% url 'GenInsuranceApp:GenInsuranceApp-mainmenu' %}" class="btn btn-danger" role="button">Mainmenu</a></p>
    {{ pform.as_p }}
    <input type="submit" value="submit" name="submit">
    </form>
{% endblock %}

templates/Master/claimstatus.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
{% csrf_token %}
    <p align="right"> <a href="{% url 'GenInsuranceApp:GenInsuranceApp-logout' %}" class="btn btn-danger" role="button">Logout</a>
     <a align="right" href="{% url 'GenInsuranceApp:GenInsuranceApp-mainmenu' %}" class="btn btn-danger" role="button">Mainmenu</a></p>
{{ cform.as_p }}
<input type="submit" value="submit" name ="submit">
</form>
{% endblock %}

templates/Master/claimsurveyor.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
{% csrf_token %}
    <p align="right"> <a href="{% url 'GenInsuranceApp:GenInsuranceApp-logout' %}" class="btn btn-danger" role="button">Logout</a>
     <a align="right" href="{% url 'GenInsuranceApp:GenInsuranceApp-mainmenu' %}" class="btn btn-danger" role="button">Mainmenu</a></p>
{{ csform.as_p }}
<input type="submit" value="submit" name="submit">
</form>
{% endblock %}

templates/Master/masterdata.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MasterPage</title>
</head>
<body>
<h2>This is my Master Page</h2>
<p align="right"> <a href="{% url 'GenInsuranceApp:GenInsuranceApp-logout' %}" class="btn btn-danger" role="button">Logout</a>
     <a align="right" href="{% url 'GenInsuranceApp:GenInsuranceApp-mainmenu' %}" class="btn btn-danger" role="button">Mainmenu</a></p>
    <p align="center"><a href="{% url 'master:master-ProductMaster' %}" class="btn btn-primary" role="button">Product</a></p>
<p align="center"><a href="{% url 'master:master-ProductRisk' %}" class="btn btn-primary" role="button">Product Risks</a></p>
<p align="center"><a href="{% url 'master:master-AgentCreate' %}" class="btn btn-primary" role="button">Create Agent</a></p>
<p align="center"><a href="{% url 'master:master-AgentCommision' %}" class="btn btn-primary" role="button">Agent Commision</a></p>
<p align="center"><a href="{% url 'master:master-vehicleMasterView' %}" class="btn btn-primary" role="button">Vehicle Master</a></p>
<p align="center"><a href="{% url 'master:master-vehicleDepreciationView' %}" class="btn btn-primary" role="button">Vehicle Depriciation</a></p>
<p align="center"><a href="{% url 'master:master-NCBMasterView' %}" class="btn btn-primary" role="button">NCB Master</a></p>
<p align="center"><a href="{% url 'master:master-ClaimStatusMasterView' %}" class="btn btn-primary" role="button">Cliam Stastus Master</a></p>
<p align="center"><a href="{% url 'master:master-ClaimsSurveyorMasterView' %}" class="btn btn-primary" role="button">Cliam Surveyor Master</a></p>
</body>
</html>

templates/Master/ncbmaster.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
{% csrf_token %}
    <p align="right"> <a href="{% url 'GenInsuranceApp:GenInsuranceApp-logout' %}" class="btn btn-danger" role="button">Logout</a>
     <a align="right" href="{% url 'GenInsuranceApp:GenInsuranceApp-mainmenu' %}" class="btn btn-danger" role="button">Mainmenu</a></p>
{{ nform.as_p }}
<input type="submit" value="submit" name="submit">
</form>
{% endblock %}

templates/Master/productRisk.html
{% extends 'base.html' %}
<title>Agent Create</title>
{% block content %}
<form method="POST">
{% csrf_token %}
<p align="right"> <a href="{% url 'GenInsuranceApp:GenInsuranceApp-logout' %}" class="btn btn-danger" role="button">Logout</a>
     <a align="right" href="{% url 'GenInsuranceApp:GenInsuranceApp-mainmenu' %}" class="btn btn-danger" role="button">Mainmenu</a></p>
<div align="center">
    <div class="row">
    <div class="col">
        {{ formset.non_form_errors.as_ul }}
        {{ formset.management_form }}
        <table id="formset" class="form">
            {% for form in formset.forms %}
                {% if forloop.first %}
                    <thead><tr>
                        {% for field in form.visible_fields %}
                        <th>{{ field.label|capfirst }}</th>
                        {% endfor %}
                    </tr></thead>
                {% endif %}
                <tr class="{% cycle row1 row2 %}">
                {% for field in form.visible_fields %}
                    <td>{% if forloop.first %}
                            {% for hidden in form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}
                        {% endif %}
                        {{ field.errors.as_ul }}
                        {{ field }}
                    </td>
                {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </div>
<button type="submit">Submit</button>
</div>
</div>
</form>
{% endblock %}

templates/Master/vehicledepriciation.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
{% csrf_token %}
    <p align="right"> <a href="{% url 'GenInsuranceApp:GenInsuranceApp-logout' %}" class="btn btn-danger" role="button">Logout</a>
     <a align="right" href="{% url 'GenInsuranceApp:GenInsuranceApp-mainmenu' %}" class="btn btn-danger" role="button">Mainmenu</a></p>
{{ vform.as_p }}
<input type="submit" value="submit" name="submit">
</form>
{% endblock %}

templates/Master/vehiclemaster.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
{% csrf_token %}
    <p align="right"> <a href="{% url 'GenInsuranceApp:GenInsuranceApp-logout' %}" class="btn btn-danger" role="button">Logout</a>
     <a align="right" href="{% url 'GenInsuranceApp:GenInsuranceApp-mainmenu' %}" class="btn btn-danger" role="button">Mainmenu</a></p>
{{ vform }}
</form>
{% endblock %}